"""Render the contract spec to language-neutral artifacts in `contract/`."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from dce.contract.spec import (
    CONTRACT_VERSION,
    MANIFEST_SCHEMA,
    MIN_HISTORY_WEEKS,
    TABLES,
    Col,
    Table,
)

_JSON_TYPES = {
    "str": "string",
    "float": "number",
    "int": "integer",
    "bool": "boolean",
    "date": "string",
    "enum": "string",
}


def _column_schema(col: Col) -> dict[str, Any]:
    base = _JSON_TYPES[col.type]
    out: dict[str, Any] = {"type": [base, "null"] if col.nullable else base}
    if col.type == "date":
        out["format"] = "date"
    if col.enum is not None:
        out["enum"] = [*col.enum, None] if col.nullable else list(col.enum)
    if col.ge is not None:
        out["minimum"] = col.ge
    if col.le is not None:
        out["maximum"] = col.le
    if col.notes:
        out["description"] = col.notes
    return out


def table_json_schema(table: Table) -> dict[str, Any]:
    """JSON Schema (draft 2020-12) for one CSV row, plus `x-` keys for table-level rules."""
    schema: dict[str, Any] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{table.name}.schema.json",
        "title": table.filename,
        "type": "object",
        "additionalProperties": False,
        "required": list(table.column_names),
        "properties": {c.name: _column_schema(c) for c in table.columns},
        "x-contract-version": CONTRACT_VERSION,
    }
    if table.notes:
        schema["description"] = table.notes
    if table.primary_key:
        schema["x-primary-key"] = list(table.primary_key)
    if table.natural_key:
        schema["x-natural-key"] = list(table.natural_key)
    if table.foreign_keys:
        schema["x-foreign-keys"] = [
            {
                "column": fk.column,
                "references": f"{fk.ref_table}.{fk.ref_column}",
                **({"separator": fk.sep} if fk.sep else {}),
                **({"when": {fk.when[0]: fk.when[1]}} if fk.when else {}),
            }
            for fk in table.foreign_keys
        ]
    if table.row_rules:
        schema["x-row-rules"] = [
            {"name": r.name, "rule": r.description, "severity": r.severity} for r in table.row_rules
        ]
    if table.monday_columns:
        schema["x-monday-columns"] = list(table.monday_columns)
    return schema


def _type_label(col: Col) -> str:
    label = " / ".join(f"`{v}`" for v in col.enum) if col.enum else col.type
    return f"{label}?" if col.nullable else label


def render_readme() -> str:
    lines = [
        "# Data contract",
        "",
        "<!-- GENERATED by `dce contract export` from backend/dce/contract/spec.py."
        " Do not edit. -->",
        "",
        f"**Version:** `{CONTRACT_VERSION}` · the only interface between `biokraft-dgp` and"
        " `biokraft-dce` (ARCH §3).",
        "",
        "## Conventions",
        "",
        "- One folder per world: `data/incoming/<world_id>/` with the 13 CSVs below plus"
        " `manifest.json`.",
        "- CSV: UTF-8, comma-separated, header row, column order free. Extra columns are"
        " ignored with a warning.",
        "- Null = empty cell. Only columns marked `?` may be null.",
        "- Dates are ISO `YYYY-MM-DD`. Weeks start Monday. Currency INR. Quantities in kg.",
        "- Booleans: `true` / `false` (case-insensitive; `1` / `0` accepted).",
        "- No ground-truth labels (no true demand, elasticity, or event flags).",
        f"- Minimum history: {MIN_HISTORY_WEEKS} weeks.",
        "- `manifest.json` is a closed schema; it must not describe the world's regime.",
        "",
        "JSON Schemas (one per CSV row, draft 2020-12) live in `schemas/`. Table-level rules"
        " are in `x-` keys: `x-primary-key` (must be unique; error), `x-natural-key`"
        " (duplicates are warnings), `x-foreign-keys`, `x-row-rules`, `x-monday-columns`.",
        "",
        "Changes: open a Contract Change request in `docs/NOTES.md`, bump the version, and"
        " regenerate.",
        "",
    ]
    for t in TABLES:
        lines += [f"## `{t.filename}`", ""]
        if t.notes:
            lines += [t.notes, ""]
        lines += ["| column | type | notes |", "|---|---|---|"]
        for c in t.columns:
            notes = [c.notes] if c.notes else []
            if c.name in t.primary_key:
                notes.insert(0, "PK")
            fks = [fk for fk in t.foreign_keys if fk.column == c.name]
            for fk in fks:
                cond = f" when {fk.when[0]}={fk.when[1]}" if fk.when else ""
                notes.append(f"FK → `{fk.ref_table}.{fk.ref_column}`{cond}")
            if c.ge is not None or c.le is not None:
                lo = "" if c.ge is None else f"≥ {c.ge:g}"
                hi = "" if c.le is None else f"≤ {c.le:g}"
                notes.append(", ".join(x for x in (lo, hi) if x))
            if c.name in t.monday_columns:
                notes.append("Monday")
            lines.append(f"| {c.name} | {_type_label(c)} | {'; '.join(notes)} |")
        lines.append("")
        if t.natural_key:
            lines += [f"Natural key: ({', '.join(t.natural_key)}).", ""]
        if t.row_rules:
            lines += ["Row rules:", ""]
            lines += [f"- {r.description} ({r.severity})" for r in t.row_rules]
            lines.append("")
    lines += ["## `manifest.json`", "", "```json", json.dumps(MANIFEST_SCHEMA, indent=2), "```", ""]
    return "\n".join(lines)


def rendered_files() -> dict[str, str]:
    """Relative path under `contract/` → file content."""
    files = {
        "CONTRACT_VERSION": CONTRACT_VERSION + "\n",
        "README.md": render_readme(),
        "schemas/manifest.schema.json": json.dumps(MANIFEST_SCHEMA, indent=2) + "\n",
    }
    for t in TABLES:
        files[f"schemas/{t.name}.schema.json"] = (
            json.dumps(table_json_schema(t), indent=2, ensure_ascii=False) + "\n"
        )
    return files


def export(contract_dir: Path) -> list[Path]:
    written = []
    for rel, content in rendered_files().items():
        path = contract_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
